import mediaManifest from "@/content/media.json";

export interface MediaMeta {
  width: number;
  height: number;
  blurDataURL: string;
}

const manifest = mediaManifest as Record<string, MediaMeta>;

/**
 * Intrinsic size + blur placeholder for images that live in /public/images.
 * Generated by `npm run blur`. Remote images (set through environment
 * variables) return undefined and fall back to an aspect-ratio container.
 */
export function getMedia(src: string): MediaMeta | undefined {
  return manifest[src];
}

export function aspectOf(src: string, fallback = 3 / 2): number {
  const meta = getMedia(src);
  return meta ? meta.width / meta.height : fallback;
}

export type Orientation = "portrait" | "landscape" | "square";

export function orientationOf(src: string): Orientation {
  const ratio = aspectOf(src);
  if (ratio > 1.15) return "landscape";
  if (ratio < 0.9) return "portrait";
  return "square";
}
