import Image from "next/image";
import { getMedia } from "@/lib/media";

/**
 * Every photograph on the site goes through here: an aspect-ratio container
 * (so nothing shifts while loading), the blur placeholder generated by
 * `npm run blur`, and responsive sizes.
 */
export function Frame({
  src,
  alt,
  sizes = "100vw",
  ratio,
  priority = false,
  className = "",
  zoom = true,
  quality = 82,
  position = "center",
}: {
  src: string;
  alt: string;
  sizes?: string;
  ratio?: number | "auto";
  priority?: boolean;
  className?: string;
  zoom?: boolean;
  quality?: number;
  position?: string;
}) {
  // No source means no frame: an empty src renders a broken box in the browser.
  if (!src) return null;

  const meta = getMedia(src);
  const resolved =
    ratio === "auto"
      ? undefined
      : (ratio ?? (meta ? meta.width / meta.height : 3 / 2));

  return (
    <div
      className={`frame ${zoom ? "frame-zoom" : ""} ${className}`.trim()}
      style={resolved ? { aspectRatio: String(resolved) } : undefined}
    >
      <Image
        src={src}
        alt={alt}
        fill
        sizes={sizes}
        quality={quality}
        priority={priority}
        loading={priority ? undefined : "lazy"}
        placeholder={meta ? "blur" : "empty"}
        blurDataURL={meta?.blurDataURL}
        style={{ objectPosition: position }}
      />
    </div>
  );
}
